
systemis = 'Arch'
systemis = 'Arch'
systemis = 'Arch'
systemis = 'Windows'
systemis = 'Arch'
systemis = 'Debian'
systemis = 'Debian'
systemis = 'Arch'
systemis = 'Debian'
systemis = 'Debian'
systemis = 'Arch'
systemis = 'Debian'
systemis = 'Arch'
systemis = 'Termux'
systemis = 'Arch'
systemis = 'Windows'